server:
  port: 80


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
#    username: ${MYSQL_USERNAME}
#    password: ${MySQL_PASSWORD}
#  mvc:
#    view:
#      suffix: .html
#      prefix: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://10.26.100.66:3306/${MYSQL_DATABASE:sjtu_checkin}
    #url: jdbc:mysql://sh-cynosdbmysql-grp-bnuzh4sa.sql.tencentcdb.com:25695/${MYSQL_DATABASE:sjtu_checkin}
    #    username: root
    #    password: bRNhbeg7
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:sjtu_checkin}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /
  redis:
    database: 0
    host: kzwkmxof.redis.bozq5jnk.q5kb4ss9.com
    #host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 10000ms

# use annotation instead of xml configuration
#mybatis:
#  mapper-locations: classpath*:mapper/*Mapper.xml